title: International Integrated Healthcare Competition
description: A site which hopefully will load
theme: just-the-docs

url: https://eugeniazanazzo.github.io/IIHC

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
