title: International Integrated Healthcare Competition
description: A site which hopefully will load
theme: just-the-docs

url: https://eugeniazanazzo.github.io/IIHC
color_scheme: iihc

search_enabled: false

aux_links:
  IIHC on Github: https://github.com/eugeniazanazzo/IIHC
